[tool.poetry]
name = "cpt"
version = "0.1.0"
description = ""
authors = ["Davi Alexandre <deltreertl@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
bs4 = "^0.0.2"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
